### PR TITLE
Make the build reproducible

### PR DESCRIPTION
**Pull request by mr-c**
See https://bugs.debian.org/946315

### CODE REVIEW

**Comment by cryptogenomicon** [comment]
I'll leave this to Eric as lead developer for the ultimate decision, but in my opinion, we would want to see a different way of addressing this issue. The proposed PR would create a difference in Infernal output file formats that depends on the setting of an environment variable at build time. We really want Infernal output formats to be consistent across platforms and builds, and this is a much higher priority for us than the objective of the reproducible-builds effort.

**Comment by cryptogenomicon** [comment]
(Also, we'd need the base branch to be `develop`, not `master`. Our master branches are stable branches that correspond to the most recent release version, and we don't modify on a master branch between releases.)

**Comment by nawrockie** [comment]
I agree with @cryptogenomicon , so I'm closing without merging.

**Comment by mr-c** [comment]
Note that we have been carrying this patch in the Debian package of infernal since 2019.

**Pull request closed without merging**
